### ISSUE TITLE
Issue rendering template

### ISSUE THREAD

**Issue by dmc2015** [balinterdi/rock-and-roll#4]
Hello,

I am trying to set up the first template but it is not rendering anything in the output of emberjs.jsbin.com.

I looked over the code for the html and js several times but nothing is being rendered and I don't see any errors.

Here is a gist of from emberjs.jsbin.com

https://gist.github.com/anonymous/c15874232d3c0bf2cca1

**Comment by balinterdi** [comment]
Hey Don,

Not sure if anything was going on, I sporadically received an error “Cannot call `create` of undefined` for the Ember.Application.create line but I’ve now updated the jsbin for the latest stable Ember version and it should work for you, too:

http://jsbin.com/famajagivo/1/edit

Thank you, this will be included in the next release.
-- 
Balint

On 21Jul 2015 at 05:18:05, don mclamb (notifications@github.com) wrote:

Hello,

I am trying to set up the first template but it is not rendering anything in the output of emberjs.jsbin.com.

I looked over the code for the html and js several times but nothing is being rendered and I don't see any errors.

Here is a gist of from emberjs.jsbin.com

https://gist.github.com/anonymous/c15874232d3c0bf2cca1

**Comment by dmc2015** [comment]
Appreciate the quick response.

Thank you.
