### ISSUE TITLE
Missing tag in Router Chapter

### ISSUE THREAD

**Issue by dmc2015** [balinterdi/rock-and-roll#6]
I noticed a missing

```HTML
<em>
```

```HTML
<!-- app/templates/bands.hbs -->
(...)
{{#each model as |band|}}
  <li class="list-group-item">{{band.name}}</em>
{{/each}}
(...)


```

tag

page 63 of the Router chapter in the ebook

**Comment by balinterdi** [comment]
Hey Don,

Great catch, thank you! I opened [an issue](https://github.com/balinterdi/rarwe-issues/issues/49) in the issues repository of the book, since this is the public, shorter version of the app we are building in the app.
